### ISSUE TITLE
Auto detect the port on which the NEATO is connected to the raspberry pi

### ISSUE THREAD

**Issue by CHARISMAlab** [CHARISMAlab/chairbot#4]
Sometimes it is /dev/ttyACM0 and some times /dev/ttyACM1.

Create a piece of code thingy to:

* Auto detect the port
* Put the port number in an XML file which the launch file supplies params from to the python code
* Have the code use that value.

**Comment by abhiagni11** [comment]
I added 99-usb-serial.rules inside ~/etc/udev/rules.d with suitable configuration for both the neato and the arduino. Now, in the refactored and new neato package, both the devices are called by /dev/neato and /dev/arduino respectively.
